# coding: utf-8

"""
    rainbond cloud app market OpenAPI.

    the purpose of this application is to provide an application that is using plain go code to define an API  This should demonstrate all the possible comment annotations that are available to turn go code into a fully compliant swagger 2.0 spec  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: 576501057@qq.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import market_client
from market_client.api.apps_api import AppsApi  # noqa: E501
from market_client.rest import ApiException


class TestAppsApi(unittest.TestCase):
    """AppsApi unit test stubs"""

    def setUp(self):
        self.api = market_client.api.apps_api.AppsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_app(self):
        """Test case for create_app

        """
        pass

    def test_create_app_version(self):
        """Test case for create_app_version

        """
        pass

    def test_download_app_by_order(self):
        """Test case for download_app_by_order

        """
        pass

    def test_get_app_version(self):
        """Test case for get_app_version

        """
        pass

    def test_get_app_versions(self):
        """Test case for get_app_versions

        """
        pass

    def test_get_app_with_version(self):
        """Test case for get_app_with_version

        """
        pass

    def test_get_apps_with_version(self):
        """Test case for get_apps_with_version

        """
        pass

    def test_get_market(self):
        """Test case for get_market

        """
        pass

    def test_get_markets(self):
        """Test case for get_markets

        """
        pass

    def test_get_recommended_app_list(self):
        """Test case for get_recommended_app_list

        get recommended app list  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
